using MediatR;
using ResourcesManagementApi.Domain.Entities;

namespace ResourcesManagementApi.Application.Commands
{
    public class ModifyResourceCommand: IRequest
    {
        public int ResourceId { get; set; }
        public Action<Resource> ModifyAction { get; set; }

        public ModifyResourceCommand(int resourceId, Action<Resource> modifyAction)
        {
            ResourceId = resourceId; // potentially could check for > 0 just in case to fail as fast as we can if id will be autogenerated (identity etc)
            ModifyAction = modifyAction ?? throw new ArgumentNullException(nameof(modifyAction));
        }
    }
}
