@host = http://localhost:5215

### login
# @name login
POST {{host}}/authentication/token
Content-Type: application/json
Accept: application/json

{
    "username": "John",
    "password": "secretpassword"
}
###

### create resource
POST {{host}}/api/resources/
Authorization: Bearer {{login.response.body.token}}
Accept: application/json
###

### withdrawn resource
PATCH {{host}}/api/resources/11/withdrawn
Authorization: Bearer {{login.response.body.token}}
Accept: application/json
###

### lock resource
PATCH {{host}}/api/resources/222/lock
Authorization: Bearer {{login.response.body.token}}
Accept: application/json
Content-Type: application/json

{
    "lockkind": 3
}

### unlock resource
PATCH {{host}}/api/resources/2/unlock
Authorization: Bearer {{login.response.body.token}}
Accept: application/json
Content-Type: application/json